import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
padding.x = 2
padding.y = 2
position.x = 40
position.y = 50
dimensions.columns = 190
dimensions.lines = 50
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font"
size = 16

[selection]
save_to_clipboard = true

[cursor]
style.shape = "Underline"
style.blinking = "On"

